development:
  adapter: postgresql
  encoding: unicode
  database: scorecard_development
  host: localhost
  pool: 5
  username: scorecard 
  password: scorecard

test:
  adapter: postgresql
  encoding: unicode
  database: scorecard_test
  host: localhost
  pool: 5
  username: scorecard
  password: scorecard

production:
  adapter: postgresql
  encoding: unicode
  database: scorecard_production
  host: localhost
  pool: 5
  username: scorecard
  password: scorecard
